"""Tracked Market Groups — manuelt kurateret research-værktøj."""

from pss.tracking.groups import (
    GroupDetail,
    GroupEventDetail,
    GroupEventSummary,
    GroupMarketRow,
    GroupSummary,
    add_event_to_group,
    add_market_to_event,
    add_market_to_group,
    add_markets_to_event,
    add_relation,
    create_group,
    ensure_market_in_db,
    get_group,
    list_events_in_group,
    list_groups,
    parse_market_reference,
    remove_event_from_group,
    remove_market_from_group,
    remove_relation,
    set_group_status,
    update_group,
)
from pss.tracking.relations import (
    RelationResult,
    evaluate_group_relations,
    evaluate_relation,
    validate_relation_definition,
)

__all__ = [
    "GroupDetail",
    "GroupEventDetail",
    "GroupEventSummary",
    "GroupMarketRow",
    "GroupSummary",
    "RelationResult",
    "add_event_to_group",
    "add_market_to_event",
    "add_market_to_group",
    "add_markets_to_event",
    "add_relation",
    "create_group",
    "ensure_market_in_db",
    "evaluate_group_relations",
    "evaluate_relation",
    "get_group",
    "list_events_in_group",
    "list_groups",
    "parse_market_reference",
    "remove_event_from_group",
    "remove_market_from_group",
    "remove_relation",
    "set_group_status",
    "update_group",
    "validate_relation_definition",
]
